# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51348666d743d8d04ceeed7f30d910a08275da37e5cd815427aa353b985f570749b1687159475e82daafabd09e36dbf4ef12fa7e89a48c9fa6ef506d97215a2e

test:
  secret_key_base: ee1cce0a8036d8a61a3d9763ff27b41be0c39124660e36e8052b8117d5ed87fc8126c54b721139befde12922d0bd5f8f7c82a699e93ca00c0b62fc178541d410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
